/**
 * 景表法 (Act against Unjustifiable Premiums and Misleading Representations) rule library.
 *
 * 20 rules covering 優良誤認 / 有利誤認 / ステマ規制 / 二重価格 等。
 * Sources:
 *   - 消費者庁「景品表示法における違反事例集」
 *   - 2023 年 10 月施行のステマ規制告示
 *   - 「No.1 表示」に関する実態調査報告書
 */
import type { JpLawRule } from "../types";

export const KEIHYOUHOU_RULES: JpLawRule[] = [
  {
    id: "JP-KEIHYO-001",
    lawCode: "keihyo",
    ruleKey: "no1_claim",
    patternType: "keyword",
    pattern: JSON.stringify(["No.1", "ナンバーワン", "業界一位", "日本一", "世界一"]),
    severity: "warning",
    descriptionJa: "「No.1」表記は客観的調査の根拠 (調査主体・期間・対象) を明示しない場合、優良誤認として景表法違反となる。",
    suggestedAlternative: "弊社調べで高評価 (調査概要: ○○年○月)",
  },
  {
    id: "JP-KEIHYO-002",
    lawCode: "keihyo",
    ruleKey: "lowest_price",
    patternType: "keyword",
    pattern: JSON.stringify(["最安値", "最低価格", "業界最安", "最安級"]),
    severity: "warning",
    descriptionJa: "最安値表記は競合調査による客観的事実が無いと有利誤認に該当しうる。",
  },
  {
    id: "JP-KEIHYO-003",
    lawCode: "keihyo",
    ruleKey: "absolute_superlative",
    patternType: "regex",
    pattern: "(完全に|絶対に|必ず|100%|全員が)",
    severity: "warning",
    descriptionJa: "絶対的表現は客観的根拠に欠けることが多く、景表法上の不当表示に該当するおそれ。",
  },
  {
    id: "JP-KEIHYO-004",
    lawCode: "keihyo",
    ruleKey: "limited_time_repeated",
    patternType: "keyword",
    pattern: JSON.stringify(["今だけ", "本日限り", "期間限定セール", "今回限り"]),
    severity: "info",
    descriptionJa: "期間限定を謳いながら常時実施している場合は有利誤認に該当する。",
  },
  {
    id: "JP-KEIHYO-005",
    lawCode: "keihyo",
    ruleKey: "fake_dual_price",
    patternType: "regex",
    pattern: "(通常価格|定価)\\s*[¥￥]?\\d+.*[→⇒]\\s*[¥￥]?\\d+",
    severity: "warning",
    descriptionJa: "販売実績のない通常価格との二重価格表示は有利誤認となる。",
  },
  {
    id: "JP-KEIHYO-006",
    lawCode: "keihyo",
    ruleKey: "free_with_strings",
    patternType: "regex",
    pattern: "(無料|タダ|0円|実質無料).{0,30}(定期|継続|サブスク|月額)",
    severity: "warning",
    descriptionJa: "無料と見せかけて定期購入条件がある場合は有利誤認。",
  },
  {
    id: "JP-KEIHYO-007",
    lawCode: "keihyo",
    ruleKey: "stealth_marketing",
    patternType: "keyword",
    pattern: JSON.stringify(["ステルスマーケティング", "ステマ", "(広告であることを隠した投稿)"]),
    severity: "error",
    descriptionJa: "広告であることを明示しない表示は 2023/10 施行のステマ規制告示違反。",
    suggestedAlternative: "[PR] / #広告 / プロモーションを含みます",
  },
  {
    id: "JP-KEIHYO-008",
    lawCode: "keihyo",
    ruleKey: "exaggerated_performance",
    patternType: "regex",
    pattern: "(他社より圧倒的|他社を凌駕|奇跡の|魔法のような)",
    severity: "warning",
    descriptionJa: "過度な性能・効果の強調は優良誤認のおそれ。",
  },
  {
    id: "JP-KEIHYO-009",
    lawCode: "keihyo",
    ruleKey: "fake_review",
    patternType: "regex",
    pattern: "(やらせ|サクラ|自作自演)\\s*(レビュー|口コミ)",
    severity: "warning",
    descriptionJa: "サクラ・自作自演の口コミ表示は不当表示として景表法違反となる。",
  },
  {
    id: "JP-KEIHYO-010",
    lawCode: "keihyo",
    ruleKey: "bait_and_switch",
    patternType: "regex",
    pattern: "(おとり広告|在庫なし|売り切れ)\\s*(でも|だが).{0,10}他.{0,10}おすすめ",
    severity: "error",
    descriptionJa: "提供できない商品で誘引し他商品を推奨するおとり広告は景表法違反。",
  },
  {
    id: "JP-KEIHYO-011",
    lawCode: "keihyo",
    ruleKey: "cashback_unconditional",
    patternType: "keyword",
    pattern: JSON.stringify(["全額返金保証", "100% 返金", "リスクゼロ"]),
    severity: "warning",
    descriptionJa: "返金条件・期限の不明示や、実質的に返金不可能な条件があれば有利誤認に該当する。",
  },
  {
    id: "JP-KEIHYO-012",
    lawCode: "keihyo",
    ruleKey: "comparison_unfair",
    patternType: "regex",
    pattern: "(A 社|B 社|他社製品).{0,20}(より|に比べて).{0,20}(優れている|高性能|安い)",
    severity: "warning",
    descriptionJa: "競合との比較は客観的根拠と公平な条件が必要。比較広告ガイドライン参照。",
  },
  {
    id: "JP-KEIHYO-013",
    lawCode: "keihyo",
    ruleKey: "ranking_no_source",
    patternType: "regex",
    pattern: "(売上ランキング|顧客満足度).{0,15}(\\d+\\s*位|第\\s*\\d+\\s*位)",
    severity: "warning",
    descriptionJa: "ランキング表示は調査主体・期間・対象を併記しないと優良誤認の対象。",
  },
  {
    id: "JP-KEIHYO-014",
    lawCode: "keihyo",
    ruleKey: "free_trial_hidden_fee",
    patternType: "regex",
    pattern: "(無料お試し|無料体験).{0,30}(継続|自動更新|解約手続き)",
    severity: "warning",
    descriptionJa: "無料お試し後の自動課金条件を分かりにくく表示することは有利誤認。",
  },
  {
    id: "JP-KEIHYO-015",
    lawCode: "keihyo",
    ruleKey: "scarcity_fake",
    patternType: "regex",
    pattern: "(残り\\s*\\d+\\s*個|在庫わずか|売り切れ間近)",
    severity: "info",
    descriptionJa: "在庫表示が常時表示・操作されている場合は不当表示に該当しうる。",
  },
  {
    id: "JP-KEIHYO-016",
    lawCode: "keihyo",
    ruleKey: "uses_official_authority_unjustified",
    patternType: "keyword",
    pattern: JSON.stringify(["公的機関認定", "国家認定", "政府推奨", "公式認可"]),
    severity: "warning",
    descriptionJa: "公的機関の認定・推奨を装う表示は事実関係の証憑が必要。",
  },
  {
    id: "JP-KEIHYO-017",
    lawCode: "keihyo",
    ruleKey: "before_after_unverified",
    patternType: "regex",
    pattern: "(before\\s*\\/\\s*after|ビフォーアフター|劇的変化)",
    severity: "warning",
    descriptionJa: "Before/After 表現は撮影条件・施術内容・個人差の併記が必要。",
  },
  {
    id: "JP-KEIHYO-018",
    lawCode: "keihyo",
    ruleKey: "premium_excess",
    patternType: "regex",
    pattern: "(豪華景品|高額プレゼント|総額\\s*\\d+\\s*万円相当)",
    severity: "info",
    descriptionJa: "景品の最高額・総額制限 (景品表示法 4 条) の遵守確認。",
  },
  {
    id: "JP-KEIHYO-019",
    lawCode: "keihyo",
    ruleKey: "endorsement_no_disclosure",
    patternType: "regex",
    pattern: "(芸能人|有名人|著名人).{0,15}(愛用|推奨|使用中)",
    severity: "warning",
    descriptionJa: "著名人による推奨は対価関係 (PR) を明示しないとステマ規制違反となる。",
  },
  {
    id: "JP-KEIHYO-020",
    lawCode: "keihyo",
    ruleKey: "scientific_unproven",
    patternType: "regex",
    pattern: "(科学的に証明|エビデンスあり|医学的に実証)",
    severity: "warning",
    descriptionJa: "「科学的根拠あり」と表示する場合は出典 (論文等) の明示が必要。出典なしは優良誤認。",
  },
];
