/**
 * 薬機法 (Pharmaceutical and Medical Devices Act) rule library.
 *
 * 20 rules covering medical / pharmaceutical / cosmetic / health-food claims
 * that exceed the regulated efficacy range. Sources:
 *   - 厚労省「医薬品等適正広告基準」
 *   - 化粧品の効能効果 56 項目
 *   - 健康食品に関する景品表示法及び健康増進法上の留意事項
 */
import type { JpLawRule } from "../types";

export const YAKKIHOU_RULES: JpLawRule[] = [
  {
    id: "JP-YAKKI-001",
    lawCode: "yakki",
    ruleKey: "disease_cure_claim",
    patternType: "keyword",
    pattern: JSON.stringify(["癌が治る", "がんが治る", "病気が治る", "難病改善", "疾患治癒", "花粉症が治る"]),
    severity: "error",
    descriptionJa: "疾病の治癒を標榜する表現は医薬品でしか広告できず、化粧品・健康食品では薬機法 66 条違反。",
    exampleViolation: "このサプリで花粉症が治る",
    suggestedAlternative: "毎日の健康習慣をサポートします",
  },
  {
    id: "JP-YAKKI-002",
    lawCode: "yakki",
    ruleKey: "anti_aging_absolute",
    patternType: "keyword",
    pattern: JSON.stringify(["シワが消える", "シワがなくなる", "アンチエイジング効果", "若返り", "細胞から再生"]),
    severity: "warning",
    descriptionJa: "化粧品の認可効能（56 項目）を逸脱したアンチエイジング表現。",
    suggestedAlternative: "うるおいによりキメを整えます",
  },
  {
    id: "JP-YAKKI-003",
    lawCode: "yakki",
    ruleKey: "supplement_medical_effect",
    patternType: "keyword",
    pattern: JSON.stringify(["血圧を下げる", "コレステロールを下げる", "血糖値改善", "血糖値を下げる"]),
    severity: "error",
    descriptionJa: "健康食品で医薬品的効能を謳うのは薬機法違反 (機能性表示食品の届出範囲を除く)。",
  },
  {
    id: "JP-YAKKI-004",
    lawCode: "yakki",
    ruleKey: "hair_growth_absolute",
    patternType: "keyword",
    pattern: JSON.stringify(["確実に生える", "毛が生える", "薄毛が完治", "発毛保証"]),
    severity: "error",
    descriptionJa: "育毛剤等での確実な効果保証は薬機法違反。",
  },
  {
    id: "JP-YAKKI-005",
    lawCode: "yakki",
    ruleKey: "diet_no_effort",
    patternType: "keyword",
    pattern: JSON.stringify(["飲むだけで痩せる", "何もしなくても痩せる", "食事制限なしで痩せる", "寝てるだけで痩せる"]),
    severity: "error",
    descriptionJa: "努力不要での痩身効果を標榜するのは薬機法・景表法の双方に抵触。",
  },
  {
    id: "JP-YAKKI-006",
    lawCode: "yakki",
    ruleKey: "side_effect_denial",
    patternType: "keyword",
    pattern: JSON.stringify(["副作用ゼロ", "副作用なし", "絶対に安全", "誰でも安心して使える"]),
    severity: "error",
    descriptionJa: "副作用が全くない旨の断言は薬機法 66 条 (誇大広告) 違反。",
  },
  {
    id: "JP-YAKKI-007",
    lawCode: "yakki",
    ruleKey: "doctor_endorsement",
    patternType: "keyword",
    pattern: JSON.stringify(["医師が推奨", "病院で採用", "厚生労働省認可", "厚労省推奨"]),
    severity: "warning",
    descriptionJa: "医薬関係者の推薦表現は適正広告基準により制限される。事実関係の確認が必要。",
  },
  {
    id: "JP-YAKKI-008",
    lawCode: "yakki",
    ruleKey: "cosmetic_acne_cure",
    patternType: "keyword",
    pattern: JSON.stringify(["ニキビが治る", "ニキビが消える", "吹き出物が消える"]),
    severity: "warning",
    descriptionJa: "化粧品の効能効果は「ニキビを防ぐ」までであり、「治る」は医薬品的表現で不可。",
    suggestedAlternative: "ニキビを防ぐ",
  },
  {
    id: "JP-YAKKI-009",
    lawCode: "yakki",
    ruleKey: "whitening_absolute",
    patternType: "keyword",
    pattern: JSON.stringify(["シミが消える", "完全に白くなる", "美白保証"]),
    severity: "warning",
    descriptionJa: "美白表現は「メラニンの生成を抑え、シミ・そばかすを防ぐ」の範囲のみ可。",
    suggestedAlternative: "メラニンの生成を抑え、シミ・そばかすを防ぐ",
  },
  {
    id: "JP-YAKKI-010",
    lawCode: "yakki",
    ruleKey: "detox_effect",
    patternType: "keyword",
    pattern: JSON.stringify(["デトックス効果", "毒素排出", "体内浄化"]),
    severity: "warning",
    descriptionJa: "デトックスや毒素排出は医薬品的効能効果に該当するおそれ。",
  },
  {
    id: "JP-YAKKI-011",
    lawCode: "yakki",
    ruleKey: "immunity_boost",
    patternType: "keyword",
    pattern: JSON.stringify(["免疫力アップ", "免疫力向上", "免疫を高める"]),
    severity: "error",
    descriptionJa: "健康食品での免疫力向上表現は薬機法上の医薬品的効能に該当。",
  },
  {
    id: "JP-YAKKI-012",
    lawCode: "yakki",
    ruleKey: "medical_device_cure",
    patternType: "keyword",
    pattern: JSON.stringify(["マッサージ器で病気が治る", "これ一つで完治", "万病に効く"]),
    severity: "error",
    descriptionJa: "医療機器の承認範囲を超える効能効果の標榜は不可。",
  },
  {
    id: "JP-YAKKI-013",
    lawCode: "yakki",
    ruleKey: "animal_disease_cure",
    patternType: "keyword",
    pattern: JSON.stringify(["ペットの病気が治る", "犬の癌改善", "猫の腎臓病が治る"]),
    severity: "error",
    descriptionJa: "動物用医薬品の承認なしでの効能標榜は不可。",
  },
  {
    id: "JP-YAKKI-014",
    lawCode: "yakki",
    ruleKey: "world_first_drug",
    patternType: "keyword",
    pattern: JSON.stringify(["世界初の治療", "業界唯一の効果", "他にはない効能"]),
    severity: "warning",
    descriptionJa: "医薬品等の最大級表現 (世界一・最高等) の使用制限。",
  },
  {
    id: "JP-YAKKI-015",
    lawCode: "yakki",
    ruleKey: "before_after_strict",
    patternType: "regex",
    pattern: "(使用前.{0,20}使用後|ビフォー.{0,5}アフター|before.{0,5}after)",
    severity: "warning",
    descriptionJa: "化粧品・医薬部外品の使用前後の比較写真は事実であっても誇大広告に該当しうる。",
  },
  {
    id: "JP-YAKKI-016",
    lawCode: "yakki",
    ruleKey: "guarantee_efficacy",
    patternType: "keyword",
    pattern: JSON.stringify(["効果保証", "返金保証付き効果", "効かなければ返金"]),
    severity: "warning",
    descriptionJa: "効果効能を保証する表現は医薬品等の適正広告基準で禁止。",
  },
  {
    id: "JP-YAKKI-017",
    lawCode: "yakki",
    ruleKey: "natural_safe_combo",
    patternType: "regex",
    pattern: "(天然成分|自然由来).{0,10}(だから|なので).{0,10}(安全|副作用なし)",
    severity: "warning",
    descriptionJa: "天然由来 = 安全という誤認を招く表現は不可。",
  },
  {
    id: "JP-YAKKI-018",
    lawCode: "yakki",
    ruleKey: "patient_testimonial",
    patternType: "regex",
    pattern: "(○○病|◯◯病|難病|末期癌).{0,15}(治った|完治した|改善した)",
    severity: "error",
    descriptionJa: "患者の体験談を用いた効能効果の保証的表現は薬機法違反。",
  },
  {
    id: "JP-YAKKI-019",
    lawCode: "yakki",
    ruleKey: "cosmetic_organ_function",
    patternType: "keyword",
    pattern: JSON.stringify(["細胞を活性化", "細胞を再生", "肌の奥深くまで浸透して効く"]),
    severity: "warning",
    descriptionJa: "化粧品で身体の組織機能の増強・増進を標榜することは認められない。",
  },
  {
    id: "JP-YAKKI-020",
    lawCode: "yakki",
    ruleKey: "unapproved_drug_import",
    patternType: "keyword",
    pattern: JSON.stringify(["個人輸入で入手可能", "海外医薬品を販売", "未承認薬の入手"]),
    severity: "error",
    descriptionJa: "未承認医薬品の広告・販売は薬機法 68 条違反。",
  },
];
